apiVersion: control.kubestellar.io/v1alpha1
kind: BindingPolicy
metadata:
  name: bg-wec2-externaldns-bindingpolicy
spec:
  wantSingletonReportedState: true
  clusterSelectors:
  - matchLabels:
      name: bg-wec2
  downsync:
  - objectSelectors:
    - matchLabels: 
        app.kubernetes.io/name: external-dns
